-- MySQL Script generated by MySQL Workbench
-- Sun Mar 20 15:48:20 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `age` VARCHAR(2) NULL,
  `phone` VARCHAR(15) NULL,
  `date` DATETIME NULL,
  `typeId` INT NULL,
  `occupationId` INT NULL,
  `educationId` INT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(50) NULL,
  `fbUserName` VARCHAR(45) NULL,
  `twUserName` VARCHAR(45) NULL,
  `about` VARCHAR(1000) NULL,
  `profileImageURL` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`catagories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`catagories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chapters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chapters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `no` INT NULL,
  `courseId` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courseDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courseDetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courseId` INT NULL,
  `summary` VARCHAR(1000) NULL,
  `objectives` VARCHAR(1000) NULL,
  `imageURL` VARCHAR(1000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courseToUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courseToUser` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courseId` INT NULL,
  `userId` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `instructorId` INT NULL,
  `catagoryId` INT NULL,
  `price` VARCHAR(10) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`educationLevels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`educationLevels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lessonLegends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lessonLegends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lessonProgress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lessonProgress` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `lessonId` INT NULL,
  `lessonLegendId` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lessonTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lessonTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lessons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courseId` INT NULL,
  `name` VARCHAR(200) NULL,
  `chapterId` INT NULL,
  `duration` VARCHAR(10) NULL,
  `typeId` VARCHAR(45) NULL,
  `fileURL` VARCHAR(200) NULL,
  `content` VARCHAR(2000) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`occupations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`occupations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paymentProcess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paymentProcess` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `courseId` INT NULL,
  `situation` VARCHAR(200) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`userTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`userTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `courseId` INT NULL,
  `stars` VARCHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`examTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`examTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`examProcess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`examProcess` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NULL,
  `chapterId` INT NULL,
  `isSuccess` INT NULL,
  `Grade` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mcTest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mcTest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `multipleChoiceTestscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
